apiVersion: v1
kind: Secret
metadata:
  labels:
    app: mongo
    tier: backend
  name: mongo-credentials
type: Opaque
data:
  password: cGFzc3dvcmQtbW9uZ28tMTIz
  user: YWRtaW4=
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
    tier: backend
  name: mongo
spec:
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: mongo
  selector:
    app: mongo
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  selector:
    matchLabels:
      app: mongo
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
        tier: backend
    spec:
      containers:
      - name: main
        # Having a pinned major and minor service version is critical
        image: mongo:3.6.21-xenial
        env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: password
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: user
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 128Mi
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - mountPath: /data/db
          name: data
      volumes:
        - name: data
          emptyDir: {}
